# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username if you have one
  - jinlong-ai

ko_fi: # Replace with your Ko-fi username
  # your-kofi-username

liberapay: # Replace with your Liberapay username
  # your-liberapay-username

open_collective: # Replace with your Open Collective username
  # your-opencollective-username

patreon: # Replace with your Patreon username
  # your-patreon-username

custom: # Replace with up to 4 custom sponsorship URLs
  - https://paypal.me/your-paypal-username
  - https://yourwebsite.com/donate
